/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import dao.DangKiMonDAO;
import dao.LopTinChiDAO;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.LopTinChi;
import model.MonHoc;

/**
 *
 * @author acer
 */
public class HuyLopTCFrame extends javax.swing.JFrame {
    private DefaultTableModel tblModel1 = new DefaultTableModel();
    /**
     * Creates new form HuyLopTCFrame
     */
    public HuyLopTCFrame() {
        initComponents();
        initTableMH();
        fillTableMH();
    }

    private void initTableMH() {
        String[] header = new String[]{"Mã Môn Học", "Tên Môn Học", "Nhóm", "Số TC Lý Thuyết", "Số TC Thực hành"};
        tblModel1.setColumnIdentifiers(header);
        tblMonHoc.setModel(tblModel1);
    }
    
    private void fillTableMH() {
        List<MonHoc> lstMonHoc = new ArrayList<>();
        try {
            DangKiMonDAO dao = new DangKiMonDAO();

            lstMonHoc = dao.getFillerLopTC();
        } catch (Exception e) {
            e.printStackTrace();
        }

        tblModel1.setRowCount(0);
        for (MonHoc monhoc : lstMonHoc) {
            tblModel1.addRow(new String[]{monhoc.getMaMon(), monhoc.getTenMon(),Integer.toString(monhoc.getNhom()), Integer.toString(monhoc.getSltclt()), Integer.toString(monhoc.getSltcth())});
        }
        tblModel1.fireTableDataChanged();
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMonHoc = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Danh sách lớp tín chỉ");

        tblMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonHocMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMonHoc);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel2.setText("Sinh viên đăng kí chưa đủ số lượng tối thiểu");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 2, 12)); // NOI18N
        jLabel3.setText("Sinh viên chưa có điểm");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 916, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(339, 339, 339)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonHocMouseClicked
        int id = tblMonHoc.rowAtPoint(evt.getPoint());
        int choice = JOptionPane.showConfirmDialog(this,"Bạn có muốn hủy không?",
        "Show Confirm Dialog ", JOptionPane.YES_NO_OPTION,
        JOptionPane.QUESTION_MESSAGE);
        if(choice == 1)
        {
            System.out.println("Ban chon NO");
        }
        else
        {
            try {
            
                String maMon = tblMonHoc.getValueAt(id, 0).toString();
                int nhom = Integer.parseInt(tblMonHoc.getValueAt(id, 2).toString());
                LopTinChi ltc = new LopTinChi();
                LopTinChiDAO ltcDAO = new LopTinChiDAO();
                int maLopTC = ltcDAO.getLTCByMaMonvaNhom(maMon, nhom);
                System.out.println(maLopTC);
                ltc = ltcDAO.getLTCByID(maLopTC);
                int slsvMin = ltc.getSlsvMin();
                DangKiMonDAO DKMdao = new DangKiMonDAO();
                boolean f = false;
                f = DKMdao.cancelLopTC(slsvMin, maLopTC);
                if (f == true) {
                    JOptionPane.showMessageDialog(this, "Hủy thành công 1 lớp tín chỉ");
                } else {
                    JOptionPane.showMessageDialog(this, "Hủy thất bại");
                }
                fillTableMH();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e.getMessage());
                e.printStackTrace();
            }
        }
        
    }//GEN-LAST:event_tblMonHocMouseClicked

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMonHoc;
    // End of variables declaration//GEN-END:variables
}
