/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import bean.DanhMucBean;
import controller.ChuyenManHinhSinhVien;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author acer
 */
public class MainSinhVienXem extends javax.swing.JFrame {
    
     
    /**
     * Creates new form MainSinhVienXem
     */
    public MainSinhVienXem(String maSV) {
        initComponents();
        setTitle("Quản Lý Sinh Viên");
        ChuyenManHinhSinhVien controller = new ChuyenManHinhSinhVien(jpnView, maSV);
        controller.setView(jpnTenSV, jlbTenSV);

        List<DanhMucBean> listItem = new ArrayList<>();
        listItem.add(new DanhMucBean("TrangChu", jpnTenSV, jlbTenSV));
        listItem.add(new DanhMucBean("SinhVienDangKi", jpnDangKi, jlbDangKi));
        listItem.add(new DanhMucBean("SinhVienXemDiem", jpnXemDiem, jlbXemDiem));
        
        controller.setEvent(listItem);
        
        jpnThoat.setVisible(true);
        jlbThoat.setVisible(true);
        
//        jlbTenSV.setText("Xin chào " + maSV);
        jlbTenSV.setText("Xin chào " + maSV.toUpperCase());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnTenSV = new javax.swing.JPanel();
        jlbTenSV = new javax.swing.JLabel();
        jpnDangKi = new javax.swing.JPanel();
        jlbDangKi = new javax.swing.JLabel();
        jpnXemDiem = new javax.swing.JPanel();
        jlbXemDiem = new javax.swing.JLabel();
        jpnThoat = new javax.swing.JPanel();
        jlbThoat = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpnMenu.setBackground(new java.awt.Color(82, 83, 83));

        jpnTenSV.setBackground(new java.awt.Color(232, 64, 60));

        jlbTenSV.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jlbTenSV.setForeground(new java.awt.Color(255, 255, 255));
        jlbTenSV.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        javax.swing.GroupLayout jpnTenSVLayout = new javax.swing.GroupLayout(jpnTenSV);
        jpnTenSV.setLayout(jpnTenSVLayout);
        jpnTenSVLayout.setHorizontalGroup(
            jpnTenSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTenSVLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbTenSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnTenSVLayout.setVerticalGroup(
            jpnTenSVLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnTenSVLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jpnDangKi.setBackground(new java.awt.Color(76, 157, 80));

        jlbDangKi.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbDangKi.setForeground(new java.awt.Color(255, 255, 255));
        jlbDangKi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_dang_ki.png"))); // NOI18N
        jlbDangKi.setText("Đăng ký tín chỉ");

        javax.swing.GroupLayout jpnDangKiLayout = new javax.swing.GroupLayout(jpnDangKi);
        jpnDangKi.setLayout(jpnDangKiLayout);
        jpnDangKiLayout.setHorizontalGroup(
            jpnDangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDangKiLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jpnDangKiLayout.setVerticalGroup(
            jpnDangKiLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnDangKiLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jpnXemDiem.setBackground(new java.awt.Color(76, 157, 80));

        jlbXemDiem.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbXemDiem.setForeground(new java.awt.Color(255, 255, 255));
        jlbXemDiem.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_ql_mon_hoc.png"))); // NOI18N
        jlbXemDiem.setText("Sinh viên xem điểm");

        javax.swing.GroupLayout jpnXemDiemLayout = new javax.swing.GroupLayout(jpnXemDiem);
        jpnXemDiem.setLayout(jpnXemDiemLayout);
        jpnXemDiemLayout.setHorizontalGroup(
            jpnXemDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnXemDiemLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbXemDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnXemDiemLayout.setVerticalGroup(
            jpnXemDiemLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnXemDiemLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbXemDiem, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(10, Short.MAX_VALUE))
        );

        jpnThoat.setBackground(new java.awt.Color(255, 153, 0));

        jlbThoat.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jlbThoat.setForeground(new java.awt.Color(255, 255, 255));
        jlbThoat.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icon_thoat.png"))); // NOI18N
        jlbThoat.setText("Đăng xuất");
        jlbThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbThoatMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jpnThoatLayout = new javax.swing.GroupLayout(jpnThoat);
        jpnThoat.setLayout(jpnThoatLayout);
        jpnThoatLayout.setHorizontalGroup(
            jpnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThoatLayout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jlbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnThoatLayout.setVerticalGroup(
            jpnThoatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnThoatLayout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jlbThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnTenSV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jpnDangKi, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnXemDiem, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnThoat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jpnTenSV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jpnDangKi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnXemDiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jpnRootLayout = new javax.swing.GroupLayout(jpnRoot);
        jpnRoot.setLayout(jpnRootLayout);
        jpnRootLayout.setHorizontalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 879, Short.MAX_VALUE)
                .addContainerGap())
        );
        jpnRootLayout.setVerticalGroup(
            jpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, 579, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(0, 0, 0))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jlbThoatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbThoatMouseClicked
        // TODO add your handling code here:
        this.dispose();
        LoginDiolog login = new LoginDiolog(this, true);
        login.setVisible(true);
    }//GEN-LAST:event_jlbThoatMouseClicked

   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jlbDangKi;
    private javax.swing.JLabel jlbTenSV;
    private javax.swing.JLabel jlbThoat;
    private javax.swing.JLabel jlbXemDiem;
    private javax.swing.JPanel jpnDangKi;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnRoot;
    private javax.swing.JPanel jpnTenSV;
    private javax.swing.JPanel jpnThoat;
    private javax.swing.JPanel jpnView;
    private javax.swing.JPanel jpnXemDiem;
    // End of variables declaration//GEN-END:variables
}
