/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import dao.MonHocDAO;
import java.lang.System.Logger;
import java.lang.System.Logger.Level;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;
import model.MonHoc;

/**
 *
 * @author acer
 */
public class MonHocPanel extends javax.swing.JPanel {
    MonHocDAO mhDAO = new MonHocDAO();
    private int demG;
    JPanel panel;
    DefaultTableModel tableModel;
    MonHoc x;
    private static int pos = 0;
    List<MonHoc> list = new ArrayList<>();
    /**
     * Creates new form MonHocPanel
     */
    public MonHocPanel() {
        initComponents();
        tableModel = (DefaultTableModel) tblMonHoc1.getModel();

        showMonHoc();
    }

    private void showMonHoc() {
        try {
            list = mhDAO.findAll();
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        tableModel.setRowCount(0);

        for (MonHoc mh : list) {
            tableModel.addRow(new Object[]{mh.getDem(), mh.getMaMon(),
                mh.getTenMon(), mh.getSltclt(), mh.getSltcth()});
        }
    }
    
     public void View() {
        x = list.get(pos);
        this.txtMaMonHoc.setText(x.getMaMon());
        this.txtMonHoc.setText(x.getTenMon());
        this.txtSLTCLT.setText("" + x.getSltclt());
        this.txtSLTCTH.setText("" + x.getSltcth());
        OnOff(false, true);
    }

    public void OnOff(boolean a, boolean b) {
        this.btnAdd.show(b);
        this.btnDelete.show(b);
        this.btnFind.show(b);
        this.btnReset.show(a);
        this.btnEdit.show(b);
        this.btnSave.show(a);

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblMonHoc = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtMaMonHoc = new javax.swing.JTextField();
        txtMonHoc = new javax.swing.JTextField();
        txtSLTCLT = new javax.swing.JTextField();
        txtSLTCTH = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnFind = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnAdd = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblMonHoc1 = new javax.swing.JTable();

        tblMonHoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã môn học", "Môn học", "STCLT", "STCTH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonHoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonHocMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblMonHoc);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Nhap thong tin"));
        jPanel2.setToolTipText("");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Mã môn học :");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Môn học :");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("STCLT :");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("STCTH :");

        txtMaMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMaMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMaMonHocActionPerformed(evt);
            }
        });

        txtMonHoc.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtMonHoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMonHocActionPerformed(evt);
            }
        });

        txtSLTCLT.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        txtSLTCLT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtSLTCLTActionPerformed(evt);
            }
        });

        txtSLTCTH.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        btnSave.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnSave.setText("Lưu");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });

        btnDelete.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnDelete.setText("Xóa ");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });

        btnFind.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnFind.setText("Tìm Kiếm");
        btnFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFindActionPerformed(evt);
            }
        });

        btnReset.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnReset.setText("Hủy bỏ");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnAdd.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnAdd.setText("Thêm");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnEdit.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        btnEdit.setText("Sửa");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtMaMonHoc, javax.swing.GroupLayout.DEFAULT_SIZE, 149, Short.MAX_VALUE)
                            .addComponent(txtSLTCLT))
                        .addGap(84, 84, 84))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btnAdd)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                        .addComponent(btnSave)))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtSLTCTH, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 99, Short.MAX_VALUE)
                        .addComponent(btnEdit)
                        .addGap(82, 82, 82)
                        .addComponent(btnDelete)
                        .addGap(178, 178, 178)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnReset)
                            .addComponent(btnFind))
                        .addGap(96, 96, 96))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(btnFind, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(17, 17, 17)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMaMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMonHoc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSLTCLT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSLTCTH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnSave, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAdd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41))
        );

        tblMonHoc1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null}
            },
            new String [] {
                "ID", "Mã môn học", "Môn học", "STCLT", "STCTH"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblMonHoc1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblMonHoc1MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tblMonHoc1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(63, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(73, 73, 73))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 276, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(64, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtMaMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMaMonHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMaMonHocActionPerformed

    private void txtMonHocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMonHocActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMonHocActionPerformed

    private void txtSLTCLTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSLTCLTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSLTCLTActionPerformed
    
    public boolean checkTrungMa(String maMon)
    {
        try {
            List<MonHoc> list = new ArrayList<>();
            list = mhDAO.findAll();
            for(MonHoc mh: list)
            {
                if(mh.getMaMon().equalsIgnoreCase(maMon))
                {
                    return true;
                }
            }
        } catch (ClassNotFoundException ex) {
            System.out.println("Err: " + ex.toString());
        }
        return false;
    }
    
    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        String id = this.txtMaMonHoc.getText();
        String monhoc = this.txtMonHoc.getText();
        int lt = Integer.parseInt(this.txtSLTCLT.getText());
        int th = Integer.parseInt(this.txtSLTCTH.getText());
        int dem = 0;
        MonHoc mh = new MonHoc(id, lt, th, dem, monhoc);

        try {
            if(checkTrungMa(mh.getMaMon()))
            {
                JOptionPane.showMessageDialog(this, "Trùng mã môn học! ");
            }
            else
            {
                mhDAO.insert(mh);
                JOptionPane.showConfirmDialog(this, "Cập nhật thành công!!", "Thông báo", JOptionPane.CLOSED_OPTION);
            }
        } catch (ClassNotFoundException ex) {
            JOptionPane.showMessageDialog(this, "ERROR!");
//            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
        }

        showMonHoc();
    }//GEN-LAST:event_btnSaveActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        int selectedIndex = tblMonHoc.getSelectedRow();
        if (selectedIndex >= 0) {
            MonHoc x = list.get(selectedIndex);

            int option = JOptionPane.showConfirmDialog(this, "Bạn muốn xóa?");

            if (option == 0) {

                try {
                    mhDAO.delete(x.getMaMon());
                    //                    JOptionPane.showConfirmDialog(panel, "Xóa thành công!!", "Thông báo", JOptionPane.CLOSED_OPTION);

                } catch (ClassNotFoundException ex) {
                    JOptionPane.showMessageDialog(panel, "ERROR!");

//                    Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
                }

                showMonHoc();
            }
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFindActionPerformed
        // TODO add your handling code here:
        String ip = JOptionPane.showInputDialog(this, "Nhập tên môn học cần tìm :");
        if (ip != null && ip.length() > 0) {
            try {
                list = mhDAO.findByFullname(ip);
            } catch (ClassNotFoundException ex) {
//                Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
            }
            tableModel.setRowCount(0);

            for (MonHoc mh : list) {
                tableModel.addRow(new Object[]{ mh.getDem(), mh.getMaMon(),
                    mh.getTenMon(), mh.getSltclt(), mh.getSltcth()});
        }

        } else {
            showMonHoc();
        }
    }//GEN-LAST:event_btnFindActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        txtMaMonHoc.setText("");
        txtMonHoc.setText("");
        txtSLTCLT.setText("");
        txtSLTCTH.setText("");
        View();
        showMonHoc();
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        txtMaMonHoc.setText("");
        txtMonHoc.setText("");
        txtSLTCLT.setText("");
        txtSLTCTH.setText("");
        OnOff(true, false);
        //        check = 1;
    }//GEN-LAST:event_btnAddActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed
        // TODO add your handling code here:

        String id = this.txtMaMonHoc.getText();
        String monhoc = this.txtMonHoc.getText();
        int lt = Integer.parseInt(this.txtSLTCLT.getText());
        int th = Integer.parseInt(this.txtSLTCTH.getText());
        int dem = demG;

        MonHoc mh = new MonHoc(id, lt, th, dem, monhoc);
        try {
            mhDAO.update(mh);
            JOptionPane.showConfirmDialog(panel, "Cập nhật thành công!!", "Thông báo", JOptionPane.CLOSED_OPTION);

        } catch (ClassNotFoundException ex) {
//            Logger.getLogger(JFrame.class.getName()).log(Level.SEVERE, null, ex);
               System.out.println("ERR: " + ex.toString());
        }

        showMonHoc();

    }//GEN-LAST:event_btnEditActionPerformed

    private void tblMonHocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonHocMouseClicked
        // TODO add your handling code here:
        pos = this.tblMonHoc.getSelectedRow();
        demG = Integer.parseInt(tblMonHoc.getValueAt(pos, 0).toString());
        View();
    }//GEN-LAST:event_tblMonHocMouseClicked

    private void tblMonHoc1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblMonHoc1MouseClicked
        // TODO add your handling code here:
//        pos = this.tblMonHoc.getSelectedRow();
//        demG = Integer.parseInt(tblMonHoc.getValueAt(pos, 0).toString());
//        View();
        int selectedIndex = this.tblMonHoc1.getSelectedRow();
    
        if (selectedIndex >= 0) {
            demG = Integer.parseInt(tblMonHoc1.getValueAt(selectedIndex, 0).toString());
            View();
        }
    }//GEN-LAST:event_tblMonHoc1MouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnFind;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnSave;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblMonHoc;
    private javax.swing.JTable tblMonHoc1;
    private javax.swing.JTextField txtMaMonHoc;
    private javax.swing.JTextField txtMonHoc;
    private javax.swing.JTextField txtSLTCLT;
    private javax.swing.JTextField txtSLTCTH;
    // End of variables declaration//GEN-END:variables
}
